default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ANONYMOUSLY_development
  password: <%= ENV['ANONYMOUSLY_DATABASE_PASSWORD'] %>
  timeout: 5000

test:
  <<: *default
  database: ANONYMOUSLY_test

production:
  <<: *default
  database: 'd8mqlonebk8953'
  username: 'bpwlooueirgvld'
  password: '4ac191e9b6f47ecaca21cffbe933d68eba0d7356d0a61c02f91b87645a445a38'
  host: 'ec2-54-83-19-244.compute-1.amazonaws.com'
  port: 5432
  